name: Deploy Streamlit App to Docker Hub and Streamlit Cloud

on:
  push:
    branches:
      - main  # 或者你使用的分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Streamlit CLI
      run: pip install streamlit

    - name: Log in to Docker Hub with GitHub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/ichingshifa-app:latest .

    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/ichingshifa-app:latest

    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deploying to Streamlit Cloud..."
        streamlit deploy your-dockerhub-username/ichingshifa-app:latest --name your-streamlit-app-name --token ${{ secrets.STREAMLIT_API_TOKEN }}
      env:
        STREAMLIT_API_TOKEN: ${{ secrets.STREAMLIT_API_TOKEN }}